import 'package:inspirelymd_patient/core/common/entities/country.dart';

const List<Country> defaultCountries = [
  Country(
    countryName: 'United States',
    countryCode: '+1',
    flag: '🇺🇸',
    isoCode: 'US',
    digitCount: 10,
    timezone: 'America/New_York',
  ),
  Country(
    countryName: 'India',
    countryCode: '+91',
    flag: '🇮🇳',
    isoCode: 'IN',
    digitCount: 10,
    timezone: 'Asia/Kolkata',
  ),
  Country(
    countryName: 'United Kingdom',
    countryCode: '+44',
    flag: '🇬🇧',
    isoCode: 'GB',
    digitCount: 10,
    timezone: 'Europe/London',
  ),
  Country(
    countryName: 'Canada',
    countryCode: '+1',
    flag: '🇨🇦',
    isoCode: 'CA',
    digitCount: 10,
    timezone: 'America/Toronto',
  ),
  Country(
    countryName: 'Australia',
    countryCode: '+61',
    flag: '🇦🇺',
    isoCode: 'AU',
    digitCount: 9,
    timezone: 'Australia/Sydney',
  ),
  Country(
    countryName: 'Germany',
    countryCode: '+49',
    flag: '🇩🇪',
    isoCode: 'DE',
    digitCount: 11,
    timezone: 'Europe/Berlin',
  ),
  Country(
    countryName: 'United Arab Emirates',
    countryCode: '+971',
    flag: '🇦🇪',
    isoCode: 'AE',
    digitCount: 9,
    timezone: 'Asia/Dubai',
  ),
  Country(
    countryName: 'Singapore',
    countryCode: '+65',
    flag: '🇸🇬',
    isoCode: 'SG',
    digitCount: 8,
    timezone: 'Asia/Singapore',
  ),
  Country(
    countryName: 'New Zealand',
    countryCode: '+64',
    flag: '🇳🇿',
    isoCode: 'NZ',
    digitCount: 9,
    timezone: 'Pacific/Auckland',
  ),
  Country(
    countryName: 'South Africa',
    countryCode: '+27',
    flag: '🇿🇦',
    isoCode: 'ZA',
    digitCount: 9,
    timezone: 'Africa/Johannesburg',
  ),
  Country(
    countryName: 'France',
    countryCode: '+33',
    flag: '🇫🇷',
    isoCode: 'FR',
    digitCount: 9,
    timezone: 'Europe/Paris',
  ),
  Country(
    countryName: 'Japan',
    countryCode: '+81',
    flag: '🇯🇵',
    isoCode: 'JP',
    digitCount: 10,
    timezone: 'Asia/Tokyo',
  ),
];
